Require the base_formatter before using it
This fixes an issue when using the rubocop rake task:
```
rake aborted!
NameError: uninitialized constant RuboCop::Formatter::BaseFormatter
```